# numpy - Numeric Python

In [1]:
import numpy as np

In [2]:
import array

## 1-d array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

## numpy automatically upcast the entire data based on higher order data

In [4]:
np.array([1,2,3,4,5,"XYZ" , 4+8j,])

array(['1', '2', '3', '4', '5', 'XYZ', '(4+8j)'], dtype='<U11')

## numpy automatically upcast the entire data based on higher order data

In [5]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

## 2-d array

In [6]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [7]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

## array with different dimnsions

In [8]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\Bharadwaj\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

## 3-d array

In [9]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

# n-dim

In [14]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

## d-type

In [15]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

## array in the form of tuples

In [11]:
np.array([(1,2) , (4,5)])

array([[1, 2],
       [4, 5]])

## int32 , int64 

In [30]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [31]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [32]:
type(arr[0][0])

numpy.int32

In [25]:
type(arr[0][1])

numpy.int64

## default : int32 or '<i4'

In [33]:
arr  = np.array([[1,3],[3,4]])

In [34]:
arr

array([[1, 3],
       [3, 4]])

In [37]:
type(arr[0][1])

numpy.int32

## Matrix (mat or matrix )

In [13]:
mat = np.mat(arr)
mat

matrix([[1, 2],
        [4, 5]])

In [12]:
mat = np.matrix(arr)
mat

matrix([[1, 2],
        [4, 5]])

## LIST to ARRAY (array or asarray or asanyarray)

In [40]:
l = [3,4,5,76,7]

In [41]:
np.array(l)

array([ 3,  4,  5, 76,  7])

## asarray:
> ##  if we apply asarray(matrix) or asarray(List) , it will be able to convert into array

In [42]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [14]:
np.asarray(mat)

array([[1, 2],
       [4, 5]])

## asanyarray:
> ## as LIST is NOT a subclass of array. So if we apply asanyarray(matrix) , it will be able to convert into array
> ## as MATRIX is a subclass of array. So if we apply asanyarray(matrix) , it wont be able to convert into array

In [43]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [45]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [46]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

## Whether matrix is the Subclass of ndarray ?
> ## True

In [15]:
issubclass( np.matrix , np.ndarray )

True

## Whether ndarray is the Subclass of  matrix?
> ## False

In [49]:
issubclass(np.ndarray,np.matrix )

False

## Deep Copy and Shallow copy

In [16]:
arr  = np.array([[1,3],[3,4]])
arr

array([[1, 3],
       [3, 4]])

## Shallow copy :
> ## Any changes made in one array will reflect in the other array

In [17]:
a = arr

## Deep copy :
> ## Any changes made in one array will NOT reflect in the other array

In [19]:
b = np.copy(arr)

In [20]:
arr[0][0] = 67

In [21]:
arr

array([[67,  3],
       [ 3,  4]])

In [22]:
a

array([[67,  3],
       [ 3,  4]])

In [23]:
b

array([[1, 3],
       [3, 4]])

## Slicing and indexing

In [58]:
arr[-1]

array([3, 4])

In [59]:
for i in arr:
    print(i)

[67  3]
[3 4]


## np.fromfunction

In [61]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [62]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [64]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [65]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

## In numpy array  $\frac{1}{0}$ is inf
## In numpy array $\frac{0}{0}$  is Not Defined

In [66]:
np.fromfunction(lambda i , j :i/j,(3,3))

<ipython-input-66-a854da4aa4ba>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
<ipython-input-66-a854da4aa4ba>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

## In python $\frac{0}{0}$ and $\frac{1}{0}$ are Not defined

In [67]:
0/0

ZeroDivisionError: division by zero

In [68]:
1/0

ZeroDivisionError: division by zero

## np.fromiter

In [32]:
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x000001E6F064FAF0>

In [33]:
def test(x):
    yield x 

In [34]:
test(5)

<generator object test at 0x000001E6F064FA98>

In [35]:
for i in gen :
    print(i)

0
1
4
9
16


In [79]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

## np.fromstring

In [36]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [86]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

## Type  :array or matrix
## ndim : Number of dimensions (Ex: 1d , 2d , 3d)
## size : Number of elements 
## shape : (rows * columns) or (depth * rows * columns )

In [87]:
l = [3,4,5,6,7,8]

In [89]:
arr = np.array(l)

In [94]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [95]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [96]:
type(arr)

numpy.ndarray

In [97]:
arr1.ndim

2

In [98]:
arr1.size

12

In [99]:
arr1.shape


(3, 4)

In [100]:
arr1.dtype

dtype('int32')

In [101]:
arr

array([3, 4, 5, 6, 7, 8])

In [102]:
arr.size

6

In [103]:
arr.ndim

1

In [104]:
arr.shape

(6,)

In [37]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [38]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [39]:
arr2.size

16

In [40]:
arr2.ndim

3

In [112]:
arr2.shape

(2, 2, 4)

In [41]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [42]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [43]:
arr4.ndim

4

In [44]:
arr4.shape

(1, 4, 2, 4)

## list(range())

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

## np.arange :
> ## Equivalent to Range Function, it also accepts Float values
> ## Incase of Floating Value , It also gives upper bound in the Output 
> ## Incase of Integer Value , It also avoids upper bound in the Output 

In [48]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [53]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [54]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

## np.linspace :
> ## default :  num = 50

In [59]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## np.zeros

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [145]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## np.ones

In [146]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

## Broadcasting

In [149]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [150]:
np.empty(5)

array([0., 0., 0., 0., 0.])

## np.empty : Randomly generated Data

In [151]:
np.empty((3,4))

array([[1.36976717e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.60952352e-072, 4.22470126e-090,
        1.80194451e+185],
       [8.31857002e-072, 1.79218578e+160, 3.99910963e+252,
        1.29200800e+161]])

## np.eye : Identity Matrix

In [152]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.linspace

In [61]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [62]:
np.linspace(2,4,4,endpoint = False)

array([2. , 2.5, 3. , 3.5])

In [63]:
np.linspace(2,4,4,endpoint = False , axis = 0)

array([2. , 2.5, 3. , 3.5])

In [68]:
np.linspace([2,4],[4,8],4,endpoint=False,axis=0)

array([[2. , 4. ],
       [2.5, 5. ],
       [3. , 6. ],
       [3.5, 7. ]])

In [69]:
np.linspace([2,4],[4,8],4,endpoint=False,axis=1)

array([[2. , 2.5, 3. , 3.5],
       [4. , 5. , 6. , 7. ]])

## np.logspace

In [70]:
np.logspace(2,3 , 5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [74]:
np.logspace([2,4],[4,8] , 5 , axis = 0)

array([[1.00000000e+02, 1.00000000e+04],
       [3.16227766e+02, 1.00000000e+05],
       [1.00000000e+03, 1.00000000e+06],
       [3.16227766e+03, 1.00000000e+07],
       [1.00000000e+04, 1.00000000e+08]])

## array.reshape()

In [93]:
d = np.linspace(0,9,10)

In [94]:
d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
d.ndim

1

In [96]:
d.shape

(10,)

In [97]:
d.reshape(10,1)

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [100]:
d.reshape(1,2,5)

array([[[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]])

In [181]:
np.logspace(2,5,10)


array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

## generate random numbers
> ## np.random.rand : Uniform Distribution
> ## np.random.randn : Standard Normal Distribution
> ## np.random.randint : Random integers

In [182]:
np.random.rand(3)

array([0.55386094, 0.36578256, 0.18724663])

In [183]:
np.random.randn(5)

array([-0.99738232, -0.29937244, -1.6336683 , -0.37804326, -0.73977523])

In [194]:
np.random.randn(2,2,3)

array([[[ 1.47338029,  0.61271404, -1.4075616 ],
        [ 0.76839332, -0.12216353, -0.09569462]],

       [[ 0.84685866,  0.53664687,  0.38711111],
        [-0.32053034,  0.53523058, -0.76029515]]])

In [203]:
np.random.randint(5,60, (4,4))

array([[30, 50, 58, 40],
       [10, 51, 38, 26],
       [19, 10, 14, 55],
       [ 8, 32, 59, 39]])

In [204]:
np.random.randn(2,2,3)

array([[[-0.18658137, -2.62084719,  0.05678706],
        [ 0.80066306,  0.32081787,  0.04011781]],

       [[-0.67044971, -0.26951513,  1.56406203],
        [ 1.70218004, -1.43323041, -1.91830673]]])

In [205]:
arr = np.random.randint(3,9, ( 3,3))

In [206]:
arr

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

## array.reshape()

In [207]:
arr.reshape(1,9)

array([[5, 3, 5, 7, 6, 4, 7, 6, 7]])

In [208]:
arr.reshape(9,1)

array([[5],
       [3],
       [5],
       [7],
       [6],
       [4],
       [7],
       [6],
       [7]])

In [209]:
arr.reshape(1,1,9)

array([[[5, 3, 5, 7, 6, 4, 7, 6, 7]]])

In [210]:
arr.reshape(3,3,1)

array([[[5],
        [3],
        [5]],

       [[7],
        [6],
        [4]],

       [[7],
        [6],
        [7]]])

## array.reshape():
> ## If one dimension is given , if we give the other dimesion as negative then , it will automatically understand the other dimension

In [215]:
arr.reshape(3,-198979)

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

In [217]:
arr.reshape(1,-145654656)

array([[5, 3, 5, 7, 6, 4, 7, 6, 7]])

## max() and min()

In [218]:
arr

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

In [219]:
arr.max()

7

In [220]:
arr.min()

3

## Indexing and Slicing

In [101]:
arr = np.random.randint(4,100, (5,5))

In [102]:
arr

array([[25,  6, 96, 70, 13],
       [32, 37, 72,  4, 88],
       [ 7, 33, 50, 26, 74],
       [17,  9, 59, 41, 32],
       [79, 21, 84, 32, 20]])

In [103]:
arr[3: , 3:]

array([[41, 32],
       [32, 20]])

In [104]:
arr[:,[1,3]]

array([[ 6, 70],
       [37,  4],
       [33, 26],
       [ 9, 41],
       [21, 32]])

In [105]:
arr

array([[25,  6, 96, 70, 13],
       [32, 37, 72,  4, 88],
       [ 7, 33, 50, 26, 74],
       [17,  9, 59, 41, 32],
       [79, 21, 84, 32, 20]])

## array Conditions

In [107]:
arr>10

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [106]:
arr[arr>10]

array([25, 96, 70, 13, 32, 37, 72, 88, 33, 50, 26, 74, 17, 59, 41, 32, 79,
       21, 84, 32, 20])

## array Multiplication
> ## array1 * array2 : Index Multiplication
>> ## Above example is not Matrix Multiplication
> ## array1 @ array2 : Matrix Multiplication

In [108]:
arr

array([[25,  6, 96, 70, 13],
       [32, 37, 72,  4, 88],
       [ 7, 33, 50, 26, 74],
       [17,  9, 59, 41, 32],
       [79, 21, 84, 32, 20]])

In [233]:
arr * arr

array([[1089, 8100, 9409,  121,   16],
       [2401, 1600, 6889, 1444, 4096],
       [  36, 2401, 9801, 7396, 9216],
       [2304, 3364, 8281, 4356,   64],
       [ 961,  576, 1156, 4096, 3844]])

In [109]:
arr1 = np.random.randint(2,4,(3,3))

In [110]:
arr2 = np.random.randint(2,4,(3,3))

In [111]:
arr1

array([[2, 2, 2],
       [2, 2, 3],
       [2, 2, 3]])

In [112]:
arr2

array([[3, 3, 2],
       [2, 2, 3],
       [3, 3, 2]])

In [113]:
arr1*arr2

array([[6, 6, 4],
       [4, 4, 9],
       [6, 6, 6]])

In [248]:
arr1@arr2

array([[22, 19, 24],
       [21, 18, 24],
       [21, 19, 24]])

# $\frac{1}{0} = \infty$

In [249]:
arr/0

<ipython-input-249-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [250]:
arr**2

array([[1089, 8100, 9409,  121,   16],
       [2401, 1600, 6889, 1444, 4096],
       [  36, 2401, 9801, 7396, 9216],
       [2304, 3364, 8281, 4356,   64],
       [ 961,  576, 1156, 4096, 3844]], dtype=int32)

## Broadcasting

In [114]:
arr = np.zeros((3,4))

In [115]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
a = np.array([1,2,3,5])

In [117]:
a


array([1, 2, 3, 5])

In [118]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [119]:
arr+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [120]:
b = np.array([5,6,7])

In [121]:
b

array([5, 6, 7])

In [122]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [123]:
b

array([5, 6, 7])

In [274]:
b = np.array([[5,6,7]])

In [277]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [278]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.sqrt , np.exp , np.log10 , 

In [279]:
arr = np.random.rand(5,4)

In [280]:
arr

array([[0.67941063, 0.39266408, 0.3690279 , 0.24322169],
       [0.73639163, 0.0401203 , 0.93684485, 0.61136987],
       [0.91075051, 0.90249311, 0.48110496, 0.24793594],
       [0.95043203, 0.31504451, 0.25094332, 0.6629506 ],
       [0.12575233, 0.45982773, 0.34866419, 0.31466519]])

In [281]:
np.sqrt(arr)

array([[0.82426369, 0.62662914, 0.60747666, 0.49317511],
       [0.85813264, 0.20030052, 0.96790746, 0.78190144],
       [0.9543325 , 0.94999637, 0.6936173 , 0.49793166],
       [0.97490104, 0.56128826, 0.50094243, 0.81421778],
       [0.35461575, 0.67810599, 0.59047794, 0.56095025]])

In [282]:
np.exp(arr)

array([[1.97271474, 1.48092083, 1.44632795, 1.27535132],
       [2.08838623, 1.04093599, 2.55191703, 1.84295428],
       [2.48618775, 2.46574282, 1.61786108, 1.28137784],
       [2.58682701, 1.3703203 , 1.28523724, 1.94050956],
       [1.13400128, 1.58380112, 1.41717322, 1.3698006 ]])

In [283]:
np.log10(arr)

array([[-0.16786766, -0.40597883, -0.4329408 , -0.6139977 ],
       [-0.13289116, -1.39663583, -0.02833232, -0.21369597],
       [-0.04060057, -0.04455611, -0.31776017, -0.60566052],
       [-0.02207894, -0.50162808, -0.60042436, -0.17851883],
       [-0.90048395, -0.33740484, -0.45759265, -0.5021513 ]])

In [284]:
arr1 = np.random.randint(2,5, (5,5))

In [290]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.60205999, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.60205999, 0.30103   , 0.60205999, 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.60205999, 0.47712125]])

In [287]:
arr1

array([[3, 3, 4, 4, 3],
       [3, 4, 4, 4, 3],
       [3, 4, 2, 4, 2],
       [3, 2, 2, 3, 3],
       [4, 3, 4, 4, 3]])

## np.random.seed : Data is same 
> ## Run the below cells with and without random.seed() Multiple times to generate Random Numbers
> ## The Data Without random.seed() changes
> ## The Data With random.seed() Remains the same

## Without random.seed

In [10]:
np.random.rand(2,4)

array([[0.1858815 , 0.98872484, 0.75008423, 0.22238605],
       [0.14790391, 0.51579028, 0.39425832, 0.06988013]])

In [11]:
np.random.rand(2,4)

array([[0.33822577, 0.01103722, 0.76752786, 0.87472213],
       [0.53359432, 0.08441275, 0.8243312 , 0.5045812 ]])

## With random.seed()

In [6]:
np.random.seed(35)
np.random.rand(2,4)

array([[0.45805495, 0.30834961, 0.23148705, 0.27742455],
       [0.81723481, 0.11134664, 0.62643723, 0.27678789]])

In [8]:
np.random.seed(35)
np.random.rand(2,4)

array([[0.45805495, 0.30834961, 0.23148705, 0.27742455],
       [0.81723481, 0.11134664, 0.62643723, 0.27678789]])