In [2]:
import numpy as np

### 1. Write a Python Program to Add Two Matrices?

In [11]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [4,5,6],
              [1,2,3]])
a+b

array([[10, 10, 10],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [43]:
def addMatrices(a,b):
    c = []
    assert a.shape == b.shape, """Please Enter matrices of Same size , 
    Two matrices Should have equal Number of Rows and Columns inorder to be added"
"""    
    for i in range(len(a)):
        for j in range(len(a[1])):
            c.append(a[i][j]+b[i][j])
    n = np.array(c)
    return n.reshape(a.shape)
    
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[9,8,7],
              [4,5,6],
              [1,2,3]])
addMatrices(a,b)

array([[10, 10, 10],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [44]:
a = np.array([[1,2,3,10],
              [4,5,6,15],
              [7,8,9,25]])
b = np.array([[9,8,7],
              [4,5,6],
              [1,2,3],
              [11,12,13]])
addMatrices(a,b)

AssertionError: Please Enter matrices of Same size , 
    Two matrices Should have equal Number of Rows and Columns inorder to be added"


### 2. Write a Python Program to Multiply Two Matrices?

In [25]:
a = np.array([[1,2,3,10],
              [4,5,6,15],
              [7,8,9,25]])
b = np.array([[9,8,7],
              [4,5,6],
              [1,2,3],
              [11,12,13]])
np.dot(a,b)

array([[130, 144, 158],
       [227, 249, 271],
       [379, 414, 449]])

In [59]:
def multiplyMatrices(a,b):
    assert a.shape[1] == b.shape[0] , "To multiply two matrices, Columns of 1st Matrix should be Equal to Rows of 2nd Matrix"
    result = np.zeros([a.shape[0],b.shape[1]])
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result
    
a = np.array([[1,2,3,10],
              [4,5,6,15],
              [7,8,9,25]])
b = np.array([[9,8,7],
              [4,5,6],
              [1,2,3],
              [11,12,13]])
multiplyMatrices(a,b)

array([[130., 144., 158.],
       [227., 249., 271.],
       [379., 414., 449.]])

In [60]:
a1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [11,12,13]])
b1 = np.array([[9,8,7],
              [4,5,6]])
multiplyMatrices(a1,b1)

AssertionError: To multiply two matrices, Columns of 1st Matrix should be Equal to Rows of 2nd Matrix

### 3. Write a Python Program to Transpose a Matrix?

In [64]:
def Transpose(a):
    t = np.zeros([a.shape[1],b.shape[0]])
    for i in range(len(a)):
        for j in range(len(a[0])):
            t[j][i] += a[i][j]
    return t

In [65]:
a1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [11,12,13]])
Transpose(a1)

array([[ 1.,  4.,  7., 11.],
       [ 2.,  5.,  8., 12.],
       [ 3.,  6.,  9., 13.]])

In [66]:
a1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [11,12,13]])
a1.T

array([[ 1,  4,  7, 11],
       [ 2,  5,  8, 12],
       [ 3,  6,  9, 13]])

### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [82]:
def SortWords(s):
    words = [i.lower() for i in s.split(" ")] 
    return sorted(words)

In [83]:
s = "Hello, My name is Bharadwaja"
SortWords(s)

['bharadwaja', 'hello,', 'is', 'my', 'name']

### 5. Write a Python Program to Remove Punctuation From a String?

In [97]:
import re
def cleanpunc(sentence): #function to clean the word of any punctuation or special characters
    cleaned = re.sub(r'[?|!|\'|>|:|"{|}|#]',r'',sentence)
    cleaned = re.sub(r'[.|,|)|(|\|/]',r' ',cleaned)
    return  cleaned
def removepunc(s):
    filtered_sentence=[]
    for w in s.split():
        for cleaned_words in cleanpunc(w).split():
            if(cleaned_words.isalpha()):    
                filtered_sentence.append(cleaned_words.lower())
    return " ".join(filtered_sentence)

In [100]:
s = """On 8 November 2016, the Government of India announced the demonetisation of all ₹500 and ₹1,000 banknotes of the Mahatma Gandhi Series. It also announced the issuance of new ₹500 and ₹2,000 banknotes in exchange for the demonetised banknotes.[1] Prime Minister Narendra Modi claimed that the action would curtail the shadow economy and reduce the use of illicit and counterfeit cash to fund illegal activity and terrorism.[2][3]

The announcement of demonetisation was followed by prolonged cash shortages in the weeks that followed, which created significant disruption throughout the economy.[4][5][6][7][8][9] People seeking to exchange their banknotes had to stand in lengthy queues, and several deaths were linked to the rush to exchange cash.[10][11]

According to a 2018 report from the Reserve Bank of India, approximately 99.3% of the demonetised banknotes, or ₹15.30 lakh crore (15.3 trillion) of the ₹15.41 lakh crore that had been demonetised, were deposited with the banking system. But the banknotes that were not deposited were worth ₹10,720 crore (107.2 billion),[12] leading analysts to state that the effort had failed to remove black money from the economy.[13][14] The BSE SENSEX and NIFTY 50 stock indices fell over 6 percent on the day after the announcement.[15] The move reduced the country's industrial production and its GDP growth rate.[16]

Initially, the move received support from several bankers as well as from some international commentators. The move was also criticised as poorly planned and unfair, and was met with protests, litigation, and strikes against the government in several places across India. Debates also took place concerning the move in both houses of Parliament.[17][18][19][20] """
print(s)

On 8 November 2016, the Government of India announced the demonetisation of all ₹500 and ₹1,000 banknotes of the Mahatma Gandhi Series. It also announced the issuance of new ₹500 and ₹2,000 banknotes in exchange for the demonetised banknotes.[1] Prime Minister Narendra Modi claimed that the action would curtail the shadow economy and reduce the use of illicit and counterfeit cash to fund illegal activity and terrorism.[2][3]

The announcement of demonetisation was followed by prolonged cash shortages in the weeks that followed, which created significant disruption throughout the economy.[4][5][6][7][8][9] People seeking to exchange their banknotes had to stand in lengthy queues, and several deaths were linked to the rush to exchange cash.[10][11]

According to a 2018 report from the Reserve Bank of India, approximately 99.3% of the demonetised banknotes, or ₹15.30 lakh crore (15.3 trillion) of the ₹15.41 lakh crore that had been demonetised, were deposited with the banking system. But 

In [101]:
removepunc(s)

'on november the government of india announced the demonetisation of all and banknotes of the mahatma gandhi series it also announced the issuance of new and banknotes in exchange for the demonetised banknotes prime minister narendra modi claimed that the action would curtail the shadow economy and reduce the use of illicit and counterfeit cash to fund illegal activity and terrorism the announcement of demonetisation was followed by prolonged cash shortages in the weeks that followed which created significant disruption throughout the economy people seeking to exchange their banknotes had to stand in lengthy queues and several deaths were linked to the rush to exchange cash according to a report from the reserve bank of india approximately of the demonetised banknotes or lakh crore trillion of the lakh crore that had been demonetised were deposited with the banking system but the banknotes that were not deposited were worth crore billion leading analysts to state that the effort had fa